import { query } from '../config/database.js'; import AppError from '../utils/AppError.js';
const select = `SELECT p.*, u.name AS creator_name FROM projects p JOIN users u ON u.id=p.created_by`;
const map = (p) => ({ ...p, techStack: p.tech_stack, githubLink: p.github_link, documentationLink: p.documentation_link, createdBy: p.created_by, createdAt: p.created_at, creator: p.creator_name });
export async function list(filters) { const where=[]; const values=[]; const add=(sql, val)=>{values.push(val);where.push(sql.replace('?', `$${values.length}`));}; if(filters.q) add(`concat_ws(' ',p.title,p.description) ILIKE '%' || ? || '%'`, filters.q); if(filters.domain) add('p.domain ILIKE ?', filters.domain); if(filters.technology) add('? = ANY(p.tech_stack)', filters.technology); if(filters.difficulty) add('p.difficulty = ?', filters.difficulty); const page=filters.page||1, limit=filters.limit||20, offset=(page-1)*limit; values.push(limit,offset); const {rows}=await query(`${select}${where.length?' WHERE '+where.join(' AND '):''} ORDER BY p.created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`, values); return rows.map(map); }
export async function get(id) { const {rows}=await query(`${select} WHERE p.id=$1`,[id]); if(!rows[0]) throw new AppError('Project not found',404); return map(rows[0]); }
export async function create(data,userId) { const {rows}=await query(`INSERT INTO projects (title,description,domain,tech_stack,github_link,documentation_link,status,difficulty,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[data.title,data.description,data.domain,data.techStack,data.githubLink||null,data.documentationLink||null,data.status||'active',data.difficulty||'intermediate',userId]); return map(rows[0]); }
export async function update(id,data,user) { const project=await get(id); if(project.createdBy!==user.id && user.role!=='admin') throw new AppError('Not allowed to edit this project',403); const fields={title:data.title,description:data.description,domain:data.domain,tech_stack:data.techStack,github_link:data.githubLink||null,documentation_link:data.documentationLink||null,status:data.status,difficulty:data.difficulty}; const sets=[],values=[]; Object.entries(fields).forEach(([k,v])=>{if(v!==undefined){values.push(v);sets.push(`${k}=$${values.length}`)}}); if(!sets.length) return project; values.push(id); const {rows}=await query(`UPDATE projects SET ${sets.join(', ')} WHERE id=$${values.length} RETURNING *`,values); return map(rows[0]); }
export async function remove(id,user) { const project=await get(id); if(project.createdBy!==user.id && user.role!=='admin') throw new AppError('Not allowed to delete this project',403); await query('DELETE FROM projects WHERE id=$1',[id]); }
export async function adopt(projectId,userId,message) { await get(projectId); const existing=await query('SELECT id FROM project_adoptions WHERE user_id=$1 AND project_id=$2',[userId,projectId]); if(existing.rowCount) throw new AppError('Adoption request already exists',409); const {rows}=await query('INSERT INTO project_adoptions (user_id,project_id,message) VALUES ($1,$2,$3) RETURNING *',[userId,projectId,message]); return rows[0]; }
export async function recommendations(id) { const project=await get(id); const {rows}=await query(`SELECT * FROM hackathons WHERE deadline >= CURRENT_DATE AND domain ILIKE $1 ORDER BY deadline ASC LIMIT 10`,[project.domain]); return rows; }
